<?php

namespace Org\Schema\Thing\CreativeWork\Article;

/**
 * Class Report.
 * A Report generated by governmental or non-governmental organization.
 * @author      AppBels <app.bels@gmail.com>
 * @name        Report
 * @namespace   Org\Schema\Thing\CreativeWork\Article
 * @package     Org\Schema
 * @see         https://schema.org/Report
 * Date         02/03/2017
 */
class Report extends \Org\Schema\Thing\CreativeWork\Article
{

	/**
	 * The number or other unique designator assigned to a Report by the publishing organization.
	 * @access  public
	 * @var     string
	 */
	public $reportNumber;

	/**
	 * Report constructor.
	 * @access  public
	 * @see     \Org\Schema\Thing\CreativeWork\Article::__construct()
	 */
	public function __construct ()
	{
		parent::__construct();
	}

	/**
	 * Report toString.
	 * @access  public
	 * @see     \Org\Schema\Thing\CreativeWork\Article::__toString()
	 *
	 * @return  string
	 */
	public function __toString ()
	{
		return parent::__toString();
	}

	/**
	 * Report destructor.
	 * @access  public
	 * @see     \Org\Schema\Thing\CreativeWork\Article::__destruct()
	 */
	public function __destruct ()
	{
		parent::__destruct();
	}

}

?>